# Generated by Django 4.2 on 2023-12-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
