# Generated by Django 4.2 on 2023-12-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientid', models.IntegerField(default=0)),
                ('sellerid', models.IntegerField(default=0)),
                ('productid', models.IntegerField(default=0)),
                ('message', models.TextField()),
                ('timestamp', models.TextField()),
                ('sendtype', models.TextField()),
                ('companyname', models.TextField()),
                ('productname', models.TextField()),
                ('clientname', models.TextField()),
                ('clientcity', models.TextField()),
            ],
        ),
    ]
